# Generated by Django 4.2.17 on 2025-03-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temperature_db',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
